apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend
  name: web-frontend-svc
  namespace: bluegreen
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30081
  selector:
    app: web-frontend
    env: main
  type: NodePort
status:
  loadBalancer: {}
