apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend
  name: web-frontend
  namespace: bluegreen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-frontend
      env: main
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-frontend
        env: main
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: labels
          mountPath: /usr/share/nginx/html
      volumes:
      - name: labels
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
status: {}
